use nom::IResult;
use ipnet::IpNet;

// IpSet is the argument that allow and deny take.
struct IpSet {
    all: bool,
    cidr: IpNet,
}

enum Line {
    Nothing,
    AcquisitionPort(i64),
    Allow(IpSet),
    BindAcqAddress(std::net::IpAddr),
    BindAddress(std::net::IpAddr),
    BindCmdAddress(std::net::IpAddr),
    // TODO: all the ones below this
    Broadcast,
    ClientLogLimit,
    CmdAllow,
    CmdDeny,
    CmdPort,
    CmdRateLimit,
    CombineLimit,
    CorrTimeRatio,
    Deny,
    Driftfile,
    Dumpdir,
    DumpOnExit,
    FallbackDrift,
    HwClockFile,
    HwTimestamp,
    Include,
    InitStepSlew,
    Keyfile,
    LeapsecMode,
    LeapsecTz,
    Local,
    LockAll,
    Log,
    LogBanner,
    LogChange,
    LogDir,
    MailOnChange,
    MakeStep,
    Manual,
    MaxChange,
    MaxClockError,
    MaxDistance,
    MaxDrift,
    MaxJitter,
    MaxSamples,
    MaxSlewRate,
    MaxUpdateSkew,
    MinSamples,
    MinSources,
    NoClientLog,
    NtpSignedSocket,
    Peer,
    Pool,
    Port,
    RateLimit,
    RefClock,
    ReselectDist,
    RtcAutoTrim,
    RtcDevice,
    RtcFile,
    RtcOnUtc,
    RtcSync,
    SchedPriority,
    Server,
    SmoothTime,
    StratumWeight,
    TempComp,
    User,
}

fn parse_line(i: &[u8]) -> IResult<&[u8], Line> {
}
